<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Todo._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <asp:Panel ID="Panel1" runat="server" BorderStyle="None" CssClass="col-md-5">
       
        <div class="form-group ">
                <asp:Label ID="lbl_addtask" CssClass="control-label" runat="server" Text="Add Task" Font-Bold="True"></asp:Label>
                <asp:TextBox ID="txt_task" runat="server"></asp:TextBox> 
                <asp:RequiredFieldValidator ID="rfv_task" runat="server" ControlToValidate="txt_task" ErrorMessage="Task can't be blank" ForeColor="Red" ValidationGroup="ADD"></asp:RequiredFieldValidator>
       </div>
        
        <div class="form-group ">

                <asp:Label ID="lbl_status" CssClass="control-label" runat="server" Text="Status" Font-Bold="True"></asp:Label>
                <asp:DropDownList ID="ddl_status" runat="server">
                    <asp:ListItem>Active</asp:ListItem>
                    <asp:ListItem>Complete</asp:ListItem>
                </asp:DropDownList>
            </div>
        <div class="form-group ">
            <asp:Button ID="btn_add" CssClass="btn btn-primary" runat="server" Text="Add Task" Font-Bold="True" OnClick="btn_add_Click" ValidationGroup="ADD"  />
        </div>
              
        
        
    </asp:Panel>

    <asp:Panel ID="Panel3" runat="server" BorderStyle="Groove" CssClass="col-md-2 text-center">
        <asp:RadioButton ID="rbtn_all" runat="server" GroupName="Checker" Text="All Tasks" AutoPostBack="True" Checked="True" OnCheckedChanged="rbtn_all_CheckedChanged" /> <br />
        <asp:RadioButton ID="rbtn_active" runat="server" Text="Active Tasks" GroupName="Checker" AutoPostBack="True" OnCheckedChanged="rbtn_active_CheckedChanged"  /> <br />
        <asp:RadioButton ID="rbtn_complete" runat="server" GroupName="Checker" Text="Completed Tasks" AutoPostBack="True" OnCheckedChanged="rbtn_complete_CheckedChanged"  /> <br />
        <asp:LinkButton ID="lbtn_delete" runat="server" Font-Bold="True" Font-Italic="True" ForeColor="Red" OnClick="lbtn_delete_Click" Font-Underline="True">Delete all Completed Tasks</asp:LinkButton>
        
        <br /> <br />

        <asp:Label ID="Label1" runat="server" Text="Total Active Tasks: " Font-Bold="True" ForeColor="#009900"></asp:Label>
        <asp:Label ID="lbl_totalactive" runat="server" ForeColor="#009900" Font-Bold="True"></asp:Label>


    </asp:Panel>

    <asp:Panel ID="Panel2" runat="server" BorderStyle="None" CssClass="col-md-5 text-center">

        <asp:GridView ID="grid_tasks" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" Font-Bold="True" AutoGenerateEditButton="True"  AutoGenerateDeleteButton="True" DataKeyNames="id" Height="196px"  Width="381px" ShowHeaderWhenEmpty="True" OnRowEditing="Grid_tasks_RowEditing" OnRowDeleting="grid_tasks_RowDeleting" EnableViewState="False" OnRowDataBound="grid_tasks_RowDataBound" >
          
            <Columns>
               
                <asp:TemplateField HeaderText="Task" SortExpression="name" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>' ></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage=" Error: Task is required" ControlToValidate="TextBox1"></asp:RequiredFieldValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Status" SortExpression="status" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle">
                    <EditItemTemplate>
                        
                        <asp:DropDownList ID="DropDownList1" runat="server" SelectedValue='<%# Bind("status") %>'>
                            <asp:ListItem>Active</asp:ListItem>
                            <asp:ListItem>Complete</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("status") %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:TemplateField>
                
            </Columns>
            <HeaderStyle  VerticalAlign="Middle" Font-Bold="True" BackColor="#CCCCCC" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:masterConnectionString %>" 
            SelectCommand="SELECT * FROM [tasks]" 
            DeleteCommand="DELETE FROM [tasks] WHERE [id] = @id" 
            InsertCommand="INSERT INTO [tasks] ([name], [status]) VALUES (@name, @status)" 
            UpdateCommand="UPDATE [tasks] SET [name] = @name, [status] = @status WHERE [id] = @id">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

        
    </asp:Panel>


</asp:Content>
